config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/gallery'
  get 'static_pages/home_owners'
  get 'static_pages/lenders'
  get 'static_pages/attorneys'
  get 'static_pages/real_estate_agents'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_contact(@contact).deliver_now
      flash[:notice] = 'Thank you for your message. We will contact you soon!'
      redirect_to root_path
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end

  private

    def contact_params
      params.require(:contact).permit(:name,:email,:message,:nickname)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def gallery
  end

  def home_owners
  end

  def lenders
  end

  def attorneys
  end

  def real_estate_agents
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="col-md-12 big">
    <div class="panel panel-default">
      <div class='panel-heading center' id='contact_header'>Contact Us</div>
      <div class='panel-body center'>
        <%= simple_form_for @contact do |f| %>
          <%= f.error_notification %>

          <div class="form-group row">
            <div class="col-md-9">
              <%= f.input :name, :required => true, placeholder: 'Name', label_html: { class: "col-md-4 col-form-label" } %>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-9">
              <%= f.input :email, :required => true, placeholder: 'Email', label_html: { class: "col-md-4 col-form-label" } %>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-9">
                <%= f.input :message, :as => :text, :required => true, :input_html => {:rows => 10, :cols => 60}, placeholder:'Tell us about your appraisal needs...', label_html: { class: 'col-md-4 col-form-label'} %>

                <div class= "hidden">
                  <%= f.input :nickname, :hint => 'Leave this field blank!' %>
                </div>
            </div>
          </div>



        <%= f.button :submit, 'Send message', :class=> "btn btn-primary btn-full" %>


        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SharpAppraisal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>

  <body>
    <%= render'shared/nav' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render'shared/footer' %>

  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <nav>
      <ul>
        <li><%= link_to 'Facebook', '#'%></li>
        <li><%= link_to 'Twitter', '#' %></li>
        <li><%= link_to 'Instagram', '#' %></li>
        <li><%= link_to 'LinkedIn', '#' %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/shared/_nav.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag("Sharp-Nav-Logo.svg", alt: "Sharp Appraisal Logo",:class => "navbar-brand") %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to 'Home', static_pages_home_path %></li>
        <li><%= link_to 'Gallery', static_pages_gallery_path %></li>
        <li><%= link_to 'Attorneys', static_pages_attorneys_path %></li>
        <li><%= link_to 'Home Owners', static_pages_home_owners_path %></li>
        <li><%= link_to 'Real Estate Agents', static_pages_real_estate_agents_path %></li>
        <li><%= link_to 'Lenders', static_pages_lenders_path %></li>
        <li><%= link_to 'About', static_pages_about_path %></li>
        <li class="active"><%= link_to 'Contact', new_contact_path %></li>
      </ul>
    </div>
  </div>
</header>

app/views/static_pages/about.html.erb
<div class="row">
  <div class="hero col-md-12">
    <div class="hero-title">
      <h1>About Page</h1>
      </div>
    <div class="hero-bg" id="about-hero-bg-img">
    </div>
  </div>
</div>

<div class="row">
  <div class="main-content col-md-12">
    <p>Carrot cake soufflé oat cake pie chocolate muffin I love candy. Muffin gingerbread gingerbread cheesecake apple pie I love Powder toffee sweet roll I love pie sweet. Pastry sweet dragée cookie sugar plum cupcake I love I love dragée. Toffee topping croissant tart cheesecake I love sweet.
    Donut pudding cheesecake. Gingerbread croissant halvah jelly lemon drops tiramisu carrot cake jelly-o. Lemon drops jujubes tootsie roll candy croissant donut.
    Tart pastry tootsie roll tiramisu tiramisu I love jujubes soufflé I love. Tiramisu powder dessert marzipan halvah halvah jelly gummies toffee. Cotton candy tootsie roll wafer. Cotton candy I love dessert bear claw halvah oat cake bear claw powder I love.
    Powder apple pie pie marzipan. Biscuit icing sugar plum. Oat cake ice cream cookie carrot cake ice cream dessert.
    Sugar plum marshmallow carrot cake ice cream powder jelly. Dragée sweet roll jelly-o candy. Dragée jelly tiramisu. Chocolate cookie jelly beans powder.</p>
  </div>
</div>

app/views/static_pages/attorneys.html.erb
<div class="row">
  <div class="hero col-md-12">
    <div class="hero-title">
      <h1>Attorneys Page</h1>
      </div>
    <div class="hero-bg" id="attorneys-hero-bg-img">
    </div>
  </div>
</div>

<div class="row">
  <div class="main-content col-md-12">
    <p>Carrot cake soufflé oat cake pie chocolate muffin I love candy. Muffin gingerbread gingerbread cheesecake apple pie I love Powder toffee sweet roll I love pie sweet. Pastry sweet dragée cookie sugar plum cupcake I love I love dragée. Toffee topping croissant tart cheesecake I love sweet.
    Donut pudding cheesecake. Gingerbread croissant halvah jelly lemon drops tiramisu carrot cake jelly-o. Lemon drops jujubes tootsie roll candy croissant donut.
    Tart pastry tootsie roll tiramisu tiramisu I love jujubes soufflé I love. Tiramisu powder dessert marzipan halvah halvah jelly gummies toffee. Cotton candy tootsie roll wafer. Cotton candy I love dessert bear claw halvah oat cake bear claw powder I love.
    Powder apple pie pie marzipan. Biscuit icing sugar plum. Oat cake ice cream cookie carrot cake ice cream dessert.
    Sugar plum marshmallow carrot cake ice cream powder jelly. Dragée sweet roll jelly-o candy. Dragée jelly tiramisu. Chocolate cookie jelly beans powder.</p>
  </div>
</div>

app/views/static_pages/gallery.html.erb
<div class="row">
  <div class="hero col-md-12">
    <div class="hero-title">
      <h1>Gallery</h1>
      <p>Lollipop apple pie gingerbread toffee cotton candy gummi bears halvah.</p>
    </div>
    <div class="hero-bg" id="gallery-hero-bg-img">
    </div>
  </div>
</div>

<div class="row">
  <div class="gallery col-md-12">
    <div class="gallery-container">

      <div class="gallery-box">
        <div class="gallery-pic">
          <%= image_tag("pic1", alt: "House1") %>
        </div>
        <div class="gallery-caption">
          <h4>Lorem Ipsum</h4>
          <p>Carrot cake soufflé oat cake pie chocolate muffin I love candy.</p>
          <button type="button" class="btn btn-default">View</button>
        </div>
      </div>

      <div class="gallery-box">
        <div class="gallery-pic">
          <%= image_tag("pic2", alt: "House2") %>
        </div>
        <div class="gallery-caption">
          <h4>Lorem Ipsum</h4>
          <p>Carrot cake soufflé oat cake pie chocolate muffin I love candy.</p>
          <button type="button" class="btn btn-default">View</button>
        </div>
      </div>

      <div class="gallery-box">
        <div class="gallery-pic">
          <%= image_tag("pic3", alt: "House3") %>
        </div>
        <div class="gallery-caption">
          <h4>Lorem Ipsum</h4>
          <p>Carrot cake soufflé oat cake pie chocolate muffin I love candy.</p>
          <button type="button" class="btn btn-default">View</button>
        </div>
      </div>

      <div class="gallery-box">
        <div class="gallery-pic">
          <%= image_tag("pic4", alt: "House4") %>
        </div>
        <div class="gallery-caption">
          <h4>Lorem Ipsum</h4>
          <p>Carrot cake soufflé oat cake pie chocolate muffin I love candy.</p>
          <button type="button" class="btn btn-default">View</button>
        </div>
      </div>

      <div class="gallery-box">
        <div class="gallery-pic">
          <%= image_tag("pic5", alt: "House5") %>
        </div>
        <div class="gallery-caption">
          <h4>Lorem Ipsum</h4>
          <p>Carrot cake soufflé oat cake pie chocolate muffin I love candy.</p>
          <button type="button" class="btn btn-default">View</button>
        </div>
      </div>

      <div class="gallery-box">
        <div class="gallery-pic">
          <%= image_tag("pic6", alt: "House6") %>
        </div>
        <div class="gallery-caption">
          <h4>Lorem Ipsum</h4>
          <p>Carrot cake soufflé oat cake pie chocolate muffin I love candy.</p>
          <button type="button" class="btn btn-default">View</button>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="home-hero col-md-12">
    <div id="logo-div">
      <%= image_tag 'SA-logo.svg', class: 'logo' %>
    </div>
</div>

  <div class="main-content col-md-12">
    <h1>Header</h1>
    <p>
      Carrot cake soufflé oat cake pie chocolate muffin I love candy. Muffin gingerbread gingerbread cheesecake apple pie I love tart marzipan croissant. Sweet roll cotton candy cake powder liquorice cupcake topping candy canes. Toffee sesame snaps bear claw pudding.
    Donut carrot cake dragée tootsie roll caramels apple pie cotton candy bear claw. Marzipan ice cream gingerbread wafer. Cookie cookie danish lemon drops chocolate sesame snaps. Pie sweet topping wafer gummi bears carrot cake.
    Tiramisu pastry oat cake cake apple pie I love. Gummi bears muffin apple pie I love. Topping candy cupcake topping.
    Lollipop apple pie gingerbread toffee cotton candy gummi bears halvah. Jujubes donut chocolate cotton candy. Lemon drops powder lemon drops cake cake. Sweet roll candy pie dessert marshmallow.
    Chocolate bar sweet marshmallow cheesecake sugar plum muffin. Bear claw chocolate bar topping danish dessert. Gummi bears sweet tootsie roll jelly-o sweet tart dessert pastry I love.
    Carrot cake soufflé oat cake pie chocolate muffin I love candy. Muffin gingerbread gingerbread cheesecake apple pie I love tart marzipan croissant. Sweet roll cotton candy cake powder liquorice cupcake topping candy canes. Toffee sesame snaps bear claw pudding.
  Donut carrot cake dragée tootsie roll caramels apple pie cotton candy bear claw. Marzipan ice cream gingerbread wafer. Cookie cookie danish lemon drops chocolate sesame snaps. Pie sweet topping wafer gummi bears carrot cake.
  Tiramisu pastry oat cake cake apple pie I love. Gummi bears muffin apple pie I love. Topping candy cupcake topping.
  Lollipop apple pie gingerbread toffee cotton candy gummi bears halvah. Jujubes donut chocolate cotton candy. Lemon drops powder lemon drops cake cake. Sweet roll candy pie dessert marshmallow.
  Chocolate bar sweet marshmallow cheesecake sugar plum muffin. Bear claw chocolate bar topping danish dessert. Gummi bears sweet tootsie roll jelly-o sweet tart dessert pastry I love.
  </p>
</div>

app/views/static_pages/home_owners.html.erb
<div class="row">
  <div class="hero col-md-12">
    <div class="hero-title">
      <h1>Home Owners</h1>
      </div>
    <div class="hero-bg" id="home-owners-hero-bg-img">
    </div>
  </div>
</div>

<div class="row">
  <div class="main-content col-md-12">
    <p>Carrot cake soufflé oat cake pie chocolate muffin I love candy. Muffin gingerbread gingerbread cheesecake apple pie I love Powder toffee sweet roll I love pie sweet. Pastry sweet dragée cookie sugar plum cupcake I love I love dragée. Toffee topping croissant tart cheesecake I love sweet.
    Donut pudding cheesecake. Gingerbread croissant halvah jelly lemon drops tiramisu carrot cake jelly-o. Lemon drops jujubes tootsie roll candy croissant donut.
    Tart pastry tootsie roll tiramisu tiramisu I love jujubes soufflé I love. Tiramisu powder dessert marzipan halvah halvah jelly gummies toffee. Cotton candy tootsie roll wafer. Cotton candy I love dessert bear claw halvah oat cake bear claw powder I love.
    Powder apple pie pie marzipan. Biscuit icing sugar plum. Oat cake ice cream cookie carrot cake ice cream dessert.
    Sugar plum marshmallow carrot cake ice cream powder jelly. Dragée sweet roll jelly-o candy. Dragée jelly tiramisu. Chocolate cookie jelly beans powder.</p>
  </div>
</div>

app/views/static_pages/lenders.html.erb
<div class="row">
  <div class="hero col-md-12">
    <div class="hero-title">
      <h1>Lenders</h1>
      </div>
    <div class="hero-bg" id="lenders-hero-bg-img">
    </div>
  </div>
</div>

<div class="row">
  <div class="main-content col-md-12">
    <p>Carrot cake soufflé oat cake pie chocolate muffin I love candy. Muffin gingerbread gingerbread cheesecake apple pie I love Powder toffee sweet roll I love pie sweet. Pastry sweet dragée cookie sugar plum cupcake I love I love dragée. Toffee topping croissant tart cheesecake I love sweet.
    Donut pudding cheesecake. Gingerbread croissant halvah jelly lemon drops tiramisu carrot cake jelly-o. Lemon drops jujubes tootsie roll candy croissant donut.
    Tart pastry tootsie roll tiramisu tiramisu I love jujubes soufflé I love. Tiramisu powder dessert marzipan halvah halvah jelly gummies toffee. Cotton candy tootsie roll wafer. Cotton candy I love dessert bear claw halvah oat cake bear claw powder I love.
    Powder apple pie pie marzipan. Biscuit icing sugar plum. Oat cake ice cream cookie carrot cake ice cream dessert.
    Sugar plum marshmallow carrot cake ice cream powder jelly. Dragée sweet roll jelly-o candy. Dragée jelly tiramisu. Chocolate cookie jelly beans powder.</p>
  </div>
</div>

app/views/static_pages/real_estate_agents.html.erb
<div class="row">
  <div class="hero col-md-12">
    <div class="hero-title">
      <h1>Real Estate Agents</h1>
      </div>
    <div class="hero-bg" id="real-estate-hero-bg-img">
    </div>
  </div>
</div>

<div class="row">
  <div class="main-content col-md-12">
    <p>Carrot cake soufflé oat cake pie chocolate muffin I love candy. Muffin gingerbread gingerbread cheesecake apple pie I love Powder toffee sweet roll I love pie sweet. Pastry sweet dragée cookie sugar plum cupcake I love I love dragée. Toffee topping croissant tart cheesecake I love sweet.
    Donut pudding cheesecake. Gingerbread croissant halvah jelly lemon drops tiramisu carrot cake jelly-o. Lemon drops jujubes tootsie roll candy croissant donut.
    Tart pastry tootsie roll tiramisu tiramisu I love jujubes soufflé I love. Tiramisu powder dessert marzipan halvah halvah jelly gummies toffee. Cotton candy tootsie roll wafer. Cotton candy I love dessert bear claw halvah oat cake bear claw powder I love.
    Powder apple pie pie marzipan. Biscuit icing sugar plum. Oat cake ice cream cookie carrot cake ice cream dessert.
    Sugar plum marshmallow carrot cake ice cream powder jelly. Dragée sweet roll jelly-o candy. Dragée jelly tiramisu. Chocolate cookie jelly beans powder.</p>
  </div>
</div>